#!/usr/bin/sh

prnt="$(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}')"

bar() {
if (( $prnt > 70 )); then
	echo "󱩖 "
elif (( $prnt > 40 )); then
	echo "󱩔 "
elif (( $prnt > 20 )); then
	echo "󱩓 "
elif (( $prnt > 10 )) || (( $prnt == 10 )); then
	echo "󱩐 "
elif (( $prnt < 10 )); then
	echo "󱧢 "
fi
}

[ "$1" == "bar" ] && bar && exit
[ "$1" == "one" ] && echo $prnt && exit
