#!/usr/bin/sh

music="$(playerctl metadata -f '{{ title }}')"
artist="$(playerctl metadata -f '{{ artist }}')"
stat="$(playerctl status)"

media() {
if [ $stat == "Playing" ]; then
	echo "$music"
elif [ $stat == "Paused" ]; then
	echo "++== Paused ==++"
elif [ $stat == "" ]; then
	echo "I don't think I Recognise What Is Playing Right Now"
else
	echo "Nothing Played Right Now"
fi
}

tooltip() {
if [ $stat == "Playing" ]; then
	echo "By: $artist"
else
	echo ""
fi
}

[ "$1" == "short" ] && media && exit
[ "$1" == "full" ] && tooltip && exit
